name: Appium CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    # strategy:
    #   matrix:
    #     include:
    #       - xcode: "13.2"
    #         ios: "15.2"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"

      - name: Use Node.js 18
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 18.18.2

      - name: Install and Run Appium Server
        run: |
          npm install -g appium@v1.22
          appium -v
          npm -g install npm
          # appium > /dev/null &

      - name: Start Appium Server
        run: |
          appium > appium.log 2>&1 &

      - name: Wait for Appium Server to Start
        run: sleep 10

      - name: Install Maven
        run: |
          brew install maven

      # - uses: futureware-tech/simulator-action@v3
      #   with:
      #       model: 'iPhone 14'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run Appium Tests
        run: mvn clean test

      - name: Upload Appium Logs
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: appium-logs
          path: |
            appium.log

      - name: upload app
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@master
        with:
          name: Debugging-SS
          path: |
            ./target/allure-results
